version: '3'
services:
  server:
    image: node:8
    container_name: 7shifts-server
    volumes:
      - "./server:/var/application/current"
    working_dir: /var/application/current
    networks:
      - default-network
    environment:
      - PORT=3001
      - USERS_URL=https://shiftstestapi.firebaseio.com/users.json
      - TIME_PUNCHES_URL=https://shiftstestapi.firebaseio.com/timePunches.json
    ports:
      - 3001:3001
    command: npm run start-dev
networks:
  default-network:
    driver: bridge
